//------------------------------------------------------------------------------
// file: UIDialogue.cs
// Author: Saro
// Time: 2021/3/28 22:28:23
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saro.UI
{
    using System.Collections;
    using UnityEngine;
    using UnityEngine.UI;


    public partial class UIDialogue : UnityEngine.MonoBehaviour
    {

        [SerializeField()]
        protected UnityEngine.UI.Text text_dialogue_title;

        [SerializeField()]
        protected UnityEngine.UI.Text text_dialogue_content;

        [SerializeField()]
        protected UnityEngine.UI.Button button_button_right;

        [SerializeField()]
        protected UnityEngine.UI.Text text_dialogue_btnright;

        [SerializeField()]
        protected UnityEngine.UI.Button button_button_left;

        [SerializeField()]
        protected UnityEngine.UI.Text text_dialogue_btnleft;

        [UnityEngine.ContextMenu("AutoBinding")]
        [System.Diagnostics.Conditional("UNITY_EDITOR")]
        private void AutoBinding()
        {
            text_dialogue_title = transform.Find("root/dialogue.title").GetComponent<Text>();
            text_dialogue_content = transform.Find("root/dialogue.content").GetComponent<Text>();
            button_button_right = transform.Find("root/button_right").GetComponent<Button>();
            text_dialogue_btnright = transform.Find("root/button_right/dialogue.btnright").GetComponent<Text>();
            button_button_left = transform.Find("root/button_left").GetComponent<Button>();
            text_dialogue_btnleft = transform.Find("root/button_left/dialogue.btnleft").GetComponent<Text>();
        }
    }
}
